### ISSUE TITLE
Motivation behind this ?

### ISSUE THREAD

**Issue by sahanatroam** [getcampsite/campkit#2]
Hi Team,
Looks neat, Whats the motive behind creating something like this ?
Why not use something like nest.js or some other framework ?

Really keen to hear your feedback as I'm defo going to try this out.

**Comment by roger-rodriguez** [comment]
Campkit was definitely inspired by projects like nest and loopback. We wanted to take some of those principals and apply them to a _**serverless first**_ environment.  

The goal is to allow developers to only focus on the logic and not on stitching together a bunch of features and services.
